[build]
publish = "dist"
command = "pnpm build"

[build.environment]
NODE_VERSION = "22.1.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
