[build]
publish = "dist"
command = "NODE_OPTIONS=--max_old_space_size=4096 npm run build"

[build.environment]
NODE_VERSION = "22.17.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
