/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/album': RouteRecordInfo<'/album', '/album', Record<never, never>, Record<never, never>>,
    '/albums/guiyang': RouteRecordInfo<'/albums/guiyang', '/albums/guiyang', Record<never, never>, Record<never, never>>,
    '/albums/kyota': RouteRecordInfo<'/albums/kyota', '/albums/kyota', Record<never, never>, Record<never, never>>,
    '/albums/pingtan': RouteRecordInfo<'/albums/pingtan', '/albums/pingtan', Record<never, never>, Record<never, never>>,
    '/albums/tokyo': RouteRecordInfo<'/albums/tokyo', '/albums/tokyo', Record<never, never>, Record<never, never>>,
    '/albums/uji': RouteRecordInfo<'/albums/uji', '/albums/uji', Record<never, never>, Record<never, never>>,
    '/anime/': RouteRecordInfo<'/anime/', '/anime', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/comment/': RouteRecordInfo<'/comment/', '/comment', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/0suiKnowledge': RouteRecordInfo<'/posts/0suiKnowledge', '/posts/0suiKnowledge', Record<never, never>, Record<never, never>>,
    '/posts/51microcopmuter': RouteRecordInfo<'/posts/51microcopmuter', '/posts/51microcopmuter', Record<never, never>, Record<never, never>>,
    '/posts/AVL树': RouteRecordInfo<'/posts/AVL树', '/posts/AVL树', Record<never, never>, Record<never, never>>,
    '/posts/B树': RouteRecordInfo<'/posts/B树', '/posts/B树', Record<never, never>, Record<never, never>>,
    '/posts/games101': RouteRecordInfo<'/posts/games101', '/posts/games101', Record<never, never>, Record<never, never>>,
    '/posts/gccSimpleLearn': RouteRecordInfo<'/posts/gccSimpleLearn', '/posts/gccSimpleLearn', Record<never, never>, Record<never, never>>,
    '/posts/JapanTravel': RouteRecordInfo<'/posts/JapanTravel', '/posts/JapanTravel', Record<never, never>, Record<never, never>>,
    '/posts/UE5_UObject': RouteRecordInfo<'/posts/UE5_UObject', '/posts/UE5_UObject', Record<never, never>, Record<never, never>>,
    '/posts/UE5_网络同步': RouteRecordInfo<'/posts/UE5_网络同步', '/posts/UE5_网络同步', Record<never, never>, Record<never, never>>,
    '/posts/UE5前置知识': RouteRecordInfo<'/posts/UE5前置知识', '/posts/UE5前置知识', Record<never, never>, Record<never, never>>,
    '/posts/VirtualFunction': RouteRecordInfo<'/posts/VirtualFunction', '/posts/VirtualFunction', Record<never, never>, Record<never, never>>,
    '/posts/zenbrowser': RouteRecordInfo<'/posts/zenbrowser', '/posts/zenbrowser', Record<never, never>, Record<never, never>>,
    '/posts/一致性哈希算法': RouteRecordInfo<'/posts/一致性哈希算法', '/posts/一致性哈希算法', Record<never, never>, Record<never, never>>,
    '/posts/九个二叉树常见问题': RouteRecordInfo<'/posts/九个二叉树常见问题', '/posts/九个二叉树常见问题', Record<never, never>, Record<never, never>>,
    '/posts/二叉树': RouteRecordInfo<'/posts/二叉树', '/posts/二叉树', Record<never, never>, Record<never, never>>,
    '/posts/似然': RouteRecordInfo<'/posts/似然', '/posts/似然', Record<never, never>, Record<never, never>>,
    '/posts/信号Matlab': RouteRecordInfo<'/posts/信号Matlab', '/posts/信号Matlab', Record<never, never>, Record<never, never>>,
    '/posts/哈希表': RouteRecordInfo<'/posts/哈希表', '/posts/哈希表', Record<never, never>, Record<never, never>>,
    '/posts/回溯算法': RouteRecordInfo<'/posts/回溯算法', '/posts/回溯算法', Record<never, never>, Record<never, never>>,
    '/posts/图': RouteRecordInfo<'/posts/图', '/posts/图', Record<never, never>, Record<never, never>>,
    '/posts/图神经网络': RouteRecordInfo<'/posts/图神经网络', '/posts/图神经网络', Record<never, never>, Record<never, never>>,
    '/posts/基础排序': RouteRecordInfo<'/posts/基础排序', '/posts/基础排序', Record<never, never>, Record<never, never>>,
    '/posts/大数据topk问题': RouteRecordInfo<'/posts/大数据topk问题', '/posts/大数据topk问题', Record<never, never>, Record<never, never>>,
    '/posts/大数据查重': RouteRecordInfo<'/posts/大数据查重', '/posts/大数据查重', Record<never, never>, Record<never, never>>,
    '/posts/数字信号处理': RouteRecordInfo<'/posts/数字信号处理', '/posts/数字信号处理', Record<never, never>, Record<never, never>>,
    '/posts/数字信号处理Matlab': RouteRecordInfo<'/posts/数字信号处理Matlab', '/posts/数字信号处理Matlab', Record<never, never>, Record<never, never>>,
    '/posts/智能指针': RouteRecordInfo<'/posts/智能指针', '/posts/智能指针', Record<never, never>, Record<never, never>>,
    '/posts/栈与队列': RouteRecordInfo<'/posts/栈与队列', '/posts/栈与队列', Record<never, never>, Record<never, never>>,
    '/posts/红黑树': RouteRecordInfo<'/posts/红黑树', '/posts/红黑树', Record<never, never>, Record<never, never>>,
    '/posts/通信原理': RouteRecordInfo<'/posts/通信原理', '/posts/通信原理', Record<never, never>, Record<never, never>>,
    '/posts/高级排序': RouteRecordInfo<'/posts/高级排序', '/posts/高级排序', Record<never, never>, Record<never, never>>,
    '/search/': RouteRecordInfo<'/search/', '/search', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__1d5cb8bb617a6832f495fc32f56d8b16/node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/.pnpm/valaxy@0.26.3_@babel+parser_aa0df0dbd699d0ffab7d9207abe04a61/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/album.md': {
      routes: '/album'
      views: never
    }
    'pages/albums/guiyang.md': {
      routes: '/albums/guiyang'
      views: never
    }
    'pages/albums/kyota.md': {
      routes: '/albums/kyota'
      views: never
    }
    'pages/albums/pingtan.md': {
      routes: '/albums/pingtan'
      views: never
    }
    'pages/albums/tokyo.md': {
      routes: '/albums/tokyo'
      views: never
    }
    'pages/albums/uji.md': {
      routes: '/albums/uji'
      views: never
    }
    'pages/anime/index.md': {
      routes: '/anime/'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/comment/index.md': {
      routes: '/comment/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'pages/notes/index.md': {
      routes: '/notes/'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__1d5cb8bb617a6832f495fc32f56d8b16/node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'pages/posts/0suiKnowledge.md': {
      routes: '/posts/0suiKnowledge'
      views: never
    }
    'pages/posts/51microcopmuter.md': {
      routes: '/posts/51microcopmuter'
      views: never
    }
    'pages/posts/AVL树.md': {
      routes: '/posts/AVL树'
      views: never
    }
    'pages/posts/B树.md': {
      routes: '/posts/B树'
      views: never
    }
    'pages/posts/games101.md': {
      routes: '/posts/games101'
      views: never
    }
    'pages/posts/gccSimpleLearn.md': {
      routes: '/posts/gccSimpleLearn'
      views: never
    }
    'pages/posts/JapanTravel.md': {
      routes: '/posts/JapanTravel'
      views: never
    }
    'pages/posts/UE5_UObject.md': {
      routes: '/posts/UE5_UObject'
      views: never
    }
    'pages/posts/UE5_网络同步.md': {
      routes: '/posts/UE5_网络同步'
      views: never
    }
    'pages/posts/UE5前置知识.md': {
      routes: '/posts/UE5前置知识'
      views: never
    }
    'pages/posts/VirtualFunction.md': {
      routes: '/posts/VirtualFunction'
      views: never
    }
    'pages/posts/zenbrowser.md': {
      routes: '/posts/zenbrowser'
      views: never
    }
    'pages/posts/一致性哈希算法.md': {
      routes: '/posts/一致性哈希算法'
      views: never
    }
    'pages/posts/九个二叉树常见问题.md': {
      routes: '/posts/九个二叉树常见问题'
      views: never
    }
    'pages/posts/二叉树.md': {
      routes: '/posts/二叉树'
      views: never
    }
    'pages/posts/似然.md': {
      routes: '/posts/似然'
      views: never
    }
    'pages/posts/信号Matlab.md': {
      routes: '/posts/信号Matlab'
      views: never
    }
    'pages/posts/哈希表.md': {
      routes: '/posts/哈希表'
      views: never
    }
    'pages/posts/回溯算法.md': {
      routes: '/posts/回溯算法'
      views: never
    }
    'pages/posts/图.md': {
      routes: '/posts/图'
      views: never
    }
    'pages/posts/图神经网络.md': {
      routes: '/posts/图神经网络'
      views: never
    }
    'pages/posts/基础排序.md': {
      routes: '/posts/基础排序'
      views: never
    }
    'pages/posts/大数据topk问题.md': {
      routes: '/posts/大数据topk问题'
      views: never
    }
    'pages/posts/大数据查重.md': {
      routes: '/posts/大数据查重'
      views: never
    }
    'pages/posts/数字信号处理.md': {
      routes: '/posts/数字信号处理'
      views: never
    }
    'pages/posts/数字信号处理Matlab.md': {
      routes: '/posts/数字信号处理Matlab'
      views: never
    }
    'pages/posts/智能指针.md': {
      routes: '/posts/智能指针'
      views: never
    }
    'pages/posts/栈与队列.md': {
      routes: '/posts/栈与队列'
      views: never
    }
    'pages/posts/红黑树.md': {
      routes: '/posts/红黑树'
      views: never
    }
    'pages/posts/通信原理.md': {
      routes: '/posts/通信原理'
      views: never
    }
    'pages/posts/高级排序.md': {
      routes: '/posts/高级排序'
      views: never
    }
    'pages/search/index.md': {
      routes: '/search/'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
